### ISSUE TITLE
fabric says that the mod requires minecraft 1.15.2 despite being marked for 1.16

### ISSUE THREAD

**Issue by Nathan22211** [williambl/piston-control#1]

**Comment by williambl** [comment]
![image](https://user-images.githubusercontent.com/5115825/75611427-46961000-5b12-11ea-9524-551a803d1404.png)

Cannot reproduce. I'll upload a new version in a minute, try with that.

**Comment by williambl** [comment]
https://github.com/williambl/piston-control/releases/tag/1.1.0
Try with this.
