### ISSUE TITLE
mod conflict - Forge version

### ISSUE THREAD

**Issue by deadspidervenom** [williambl/piston-control#2]
So it took me a bit to figure this out and ill will be posting this on their github issues as well as the topic i found that explained it also had this issue.

the quote from this topic https://github.com/13rac1/Minecraft-Water-Erosion/issues/10

> This issue here is caused by your mod `water-erosion` and `immersive-portals` having the same refmap name `main.refmap.json`, whats happening is your refmap is getting overwritten by `immersive-portals` which is then obviously causing major issues.
> 
> The fix for this is to simply rename your refmap so that it contains your mod id. Example: `erosion.refmap.json`, this needs to be changed in your `build.gradle` and the `refmap` entry in `erosion.mixins.json`

At least thats my hope, as i removed your mod and things loaded.

EDIT: post i made on immersive portals github. https://github.com/qouteall/ImmersivePortalsModForForge/issues/103

**Comment by williambl** [comment]
Thanks for reporting, but this should be in [williambl/piston-control-forge](https://github.com/williambl/piston-control-forge).

My refmap is set to `pistoncontrol.refmap.json`, so there shouldn't be any conflicts there. Could you send the full log on gist, pastebin or similar, in a new issue on the forge repo? Thanks again for reporting this.

**Comment by deadspidervenom** [comment]
Alright, might want to change the forge page then, cause the issues option sent me here

**Comment by williambl** [comment]
Ah, thanks.
